### ISSUE TITLE
Проработать динамический рендеринг на фронте

### ISSUE THREAD

**Issue by IlyaTsaplin** [frostsergei/battery-devices-master#16]
Исследовать подходы к динамическому рендерингу в Angular.
Сформировать находки и идеи в виде документа на вики

**Comment by go1vs1noob** [comment]
Есть библиотека [Formly](https://formly.dev/docs/examples/advanced/json-schema) (см. вкладку `schema_dependencies` и есть кнопочка справа чтобы посмотреть код). Там по json-ине генерируются формочки (даже зависимости от наличия инпутов можно прописывать), вроде как прикручивается кастомная валидация. Возникает вопрос - как отключать одну форму в зависимости от значения в другой (а не наличия другой) - думаю это на беке можно фильтровать по ямлику перед, например, генерацией json-ины для этой библы (может сразу фильтровать и зависимости от других инпутов?). Вроде можно [подбирать json-схему сразу с сервака](https://formly.dev/docs/examples/other/json-powered), но пока не понятно, будет ли полный функционал (зависимости и пр.)
Глянул пару других вариантов - там нет возможности прописать зависимости.

**Comment by go1vs1noob** [comment]
[Закинул небольшое введение в библу сюда](https://github.com/frostsergei/battery-devices-master/wiki/%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B8%D0%BD%D0%B3-%D0%BD%D0%B0-%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5)
