### ISSUE TITLE
Техпроработка структуры и принципов работы конфигурационного файла

### ISSUE THREAD

**Issue by IlyaTsaplin** [frostsergei/battery-devices-master#3]
Описать структуру и вид конфигурационного JSON, на основе которго должны генерироваться экраны для ввода параметров на фронте.
Нужно учесть сложные параметры, и то как потом генерировать XML файл.
В конце сформировать требования для вики

**Comment by purposelessness** [comment]
[Добавил страницу, описывающую настройки (пока, в основном, параметры)](https://github.com/frostsergei/battery-devices-master/wiki/Настройки)

**Comment by purposelessness** [comment]
Я не уверен, как минимум, в том, необходимы ли нам следующие настройки:
- `less`
- `default`
- `regex`

Плюс, я пока не создавал схему по тем параметрам, что нам требуются, но набросал, какое у меня представление по устройству этих параметров: пишем в ямликах, задаём ограничения, а потом на клиенте валидируем по этим вот конфигам. 
Конфиг для отображения будет содержать имена параметров, распределённых кое-каким образом (пока не знаю как конкретно.....)

**Comment by go1vs1noob** [comment]
Как я понял, `less: string` в условиях параметров нужен в случае, когда параметр существует только если у другого параметра значение меньше какого-то конкретного? Может тогда попробовать навесить полноценную проверку по фильтрам, которые ты описывал?

`regex` я бы оставил, учитывая что во многих полях нужен прям определённый формат. 

Также не понял `mode: enum - optional` - моё понимание из описания такое: параметр можно сделать `required` (дать возможность пользователю поменять значение с `default`) или сделать `disabled` (неизменяемое пользователем `default` значение пойдёт в БД) в ямле - и, исходя из этого, параметр генерируется или не генерируется в конструкторе окон. Поправь если неправильно и какое вообще у тебя видение.

А так - выглядит хорошо.

**Comment by purposelessness** [comment]
> Также не понял зачем `mode: enum - optional` - моё понимание из описания такое: параметр можно сделать `required` (дать возможность пользователю поменять значение с `default`), или сделать `disabled` (неизменяемое пользователем `default` значение пойдёт в БД) в ямле - и, исходя из этого, инпут, отвечающий за параметр, генерируется или не генерируется в приложении. Поправь если неправильно, и какое вообще у тебя видение?

Наверное да, согласен, что-то перемудрил. Кажется, настройки `required: boolean` будет достаточно.

**Comment by IlyaTsaplin** [comment]
Пара вопросов при чтении возникла:

1. `nullable: boolean — может ли параметр принимать нулевое значение (по умолчанию false);`

Что значит нулевой значение?  Т.е. можем ли мы его в форме пропустить при заполнении?

2. `array — динамический список пользовательских значений определённого типа;`
А как такой список будет в форме задаваться? Где будем использовать такой параметр?

3. `Составной параметр — объект, объединяющий несколько параметров в рамках одного параметра.`
Как именно будет объединение происходить? Будем приводить всё к строке и склеивать? Нужно дописать
Будем ли мы позволять склеивать составные параметры? Если нет, то надо это дописать, чтобы потом поддержать в коде. Тут возникает задача валидации заданного конфига.

В остальном всё хорошо, можно дооформлять и показывать.

**Comment by purposelessness** [comment]
@IlyaTsaplin добавил уточняющие алерты, немножко изменил условия, пояснил *группирующую* роль составного параметра и дописал устройство «конструктора окон»

**Comment by purposelessness** [comment]
Доработка будет производиться в рамках [этого тикета](https://github.com/frostsergei/battery-devices-master/issues/13).
