### ISSUE TITLE
Конфиг для клиента

### ISSUE THREAD

**Issue by IlyaTsaplin** [frostsergei/battery-devices-master#34]
1. Ручку api/JsonSchema меняем на api/YamlSchema
2. Раскрываем параметры (шаблоны, циклы и т. п.) в схеме
3. В ручке сливаем два файла из config/parameters.yaml и config/form.yaml в один и отправляем

**Comment by purposelessness** [comment]
По итогу в задаче был реализован парсер и большая часть валидаторов для схемы параметров.
