### ISSUE TITLE
Макет UI

### ISSUE THREAD

**Issue by IlyaTsaplin** [frostsergei/battery-devices-master#5]
Нарисовать макет в Figma. Красота на усмотрение

**Comment by purposelessness** [comment]
> Сделал, можно посмотреть как выглядит [здесь](https://www.figma.com/proto/8thl5l8fexhr8DioMIhiOl/battery-devices?type=design&node-id=1-125&t=dw0MRvB7phMmXGQm-1&scaling=contain&page-id=0%3A1&mode=design) или изменить что-то [здесь](https://www.figma.com/file/8thl5l8fexhr8DioMIhiOl/battery-devices?type=design&node-id=0%3A1&mode=design&t=3k3uhZ0sDur35jDQ-1).

Хмм 🤔, а мне, кстати говоря, нравится такой подход! 

1. Правда, не понимаю, зачем явно разделять простые параметры и сложные (хотя на самом деле это не сложные, а составные параметры).
  - Есть *атомарные* параметры: простые и сложные параметры. 
  - Есть составные параметры, состоящие из атомарных параметров. 

2. Можно реально сделать несколько окон, а в каждом окне сделать выпадающий список с неким списком параметров, которые можно изменить в рамках этого окна. Ты выбираешь нужный параметр, изменяешь его. В этом списке нужно бы ещё отображать статус параметра:
  - обязательный, но незаполненный (пустой квадратик)
  - обязательный, но заполненный (зелёная галочка)
  - необязательный, но незаполненный (например, серая галочка)
  - обязательный и заполненный (зелёная галочка)

    Ну, эмодзи какое-то добавить, просто в качестве примера привёл, как вижу.

    Вообще, если уж и разделять параметры, можно сделать для вкладки 2 отдельных списка с параметрами: с атомарными и составными, — которые относятся к данному слайду. Вообще так, да, будет проще реализовать:) При таком взгляде твой макет выглядит как раз верно; правда, нужно бы ещё нарисовать, как будет выглядеть вкладка при выбранных параметрах.

3. Ещё нужно добавить `?` (кружок с вопросиком) рядом с названием параметра, в котором бы выводилось, как минимум, описание.

В рамках MVP такого макета должно быть достаточно, вроде как. Далее уже посмотрим, насколько это удобно и стоит ли делать не простым списком параметры, а сразу их все размещать во вкладке.

**Comment by go1vs1noob** [comment]
> не понимаю, зачем явно разделять простые параметры и сложные

И вправду незачем, добавил просто для разнообразия.
> В этом списке нужно бы ещё отображать статус параметра

Согласен, можно ещё выделять поле инпут разными цветами, ну и подсказки маленькими буквами снизу писать, но думаю это уже позже решим когда реализовывать будем
> Можно реально сделать несколько вкладок, а в каждой вкладке сделать выпадающий список с неким списком параметров, которые можно изменить в рамках этой вкладки.

Типа как в аккордионе? Просто в этом прототипе "вкладки" (ну или окна) в виде степпера, но аккордионом было бы тоже удобно пользоваться, можем обсудить с ребятами.

> нужно бы ещё нарисовать, как будет выглядеть вкладка при выбранных параметрах

Вот тут не понял о чём ты. Можешь пример привести?

> нужно добавить ? (кружок с вопросиком) рядом с названием параметра, в котором бы выводилось, как минимум, описание

Тоже согласен, обязательно сделаем.
