### ISSUE TITLE
Настроить форматтер для TypeScript

### ISSUE THREAD

**Issue by IlyaTsaplin** [frostsergei/battery-devices-master#9]
Добавить проверку форматирования для .ts файлов на pull-request'ы

**Comment by purposelessness** [comment]
А, как я понял, eslint имеет уже готовые настройки линтера:
```js
{
    "extends": "eslint:recommended"
}
```
А форматтер настраивается вручную?

**Comment by purposelessness** [comment]
> > А, как я понял, eslint имеет уже готовые настройки линтера:
> > ```js
> > {
> >     "extends": "eslint:recommended"
> > }
> > ```
> 
> Да но это для js, с ts кодом будет конфликтовать. Есть настройки специально для ts
> 
> ```js
> {
>     "extends":"plugin:@typescript-eslint/recommended"
> } 
> ```
> 
> Но там проверка в основном на подобные признаки, а не на формат кода:
> 
> 1. noUnusedVars: Предупреждает об неиспользуемых переменных.
> 2. noUnusedParameters: Предупреждает об неиспользуемых параметрах функций.
> 
> > А форматтер настраивается вручную?
> 
> Поэтому надо настраивать вручную через rules. Но ещё поищу расширения на проверку формата для ts, либо другие инструменты проверки формата.

О, вроде оно — [утилита от гугла](https://github.com/google/gts). М?

**Comment by Allonario** [comment]
> > Поэтому надо настраивать вручную через rules. Но ещё поищу расширения на проверку формата для ts, либо другие инструменты проверки формата.
> 
> О, вроде оно — [утилита от гугла](https://github.com/google/gts). М?

Хорошо, посмотрю

**Comment by Allonario** [comment]
> > Поэтому надо настраивать вручную через rules. Но ещё поищу расширения на проверку формата для ts, либо другие инструменты проверки формата.
> 
> О, вроде оно — [утилита от гугла](https://github.com/google/gts). М?

Там возникают проблемы, что он ругается на символ возврата каретки (␍) при каждом переносе строки, т.к. видимо там стандарт для unix систем, плюс при работе github actions возникает ошибка, связанная с окружением, которое github actions создаёт, не знаю как пофиксить. Пока всё-таки попробую через rules правила форматирования задать.

**Comment by purposelessness** [comment]
> Там возникают проблемы, что он ругается на символ возврата каретки (␍) при каждом переносе строки, т.к. видимо там стандарт для unix систем

Вообще символ каретки нужно бы действительно удалять перед коммитом:) 

> плюс при работе github actions возникает ошибка

Печально, понял.

**Comment by Allonario** [comment]
Вроде нашёл оптимальный вариант. Совместил модуль от prettier и несколько правил на форматирование импортов (пустая строка между импортами фреймворка и локальными файлами, плюс сортировка внутри групп в алфавитном порядке файлов)

**Comment by Allonario** [comment]
Для проверки корректности формата используется команда
```
npm run lint
```
Для исправления ошибок форматирования, которые позволяют сделать это быстро используется команда
```
npm run lint-fix
```
